/**
 * GENERATED by scripts/i18n.mjs from docs/i18n-review.md. Do not hand-edit.
 *
 * REVIEWED — the keys whose translation Max has read and signed. Anything absent
 * renders in English; see the note at the top of the review file.
 *
 * COMPLETE_LOCALES — the locales with nothing left to review. A locale outside
 * this list is built but not published: no index, no sitemap entry, no switcher.
 */
export const REVIEWED: ReadonlySet<string> = new Set([
  "uk:thanks.heading"
]);

export const COMPLETE_LOCALES: readonly string[] = [];
