#!/usr/bin/env node
/**
 * Subset the web fonts to the characters this site actually uses.
 *
 * The brief asks for subset fonts. What was shipping before was Google's *script*
 * subset — every latin glyph, including hundreds this site will never render.
 * This cuts them to the characters present in the built HTML plus a safety set,
 * which measurably shortens the critical path: those files are preloaded, so
 * every kilobyte in them is a kilobyte in front of the first paint.
 *
 * Run after a build, then build again so the hashes and the CSS line up:
 *   npm run build && npm run fonts && npm run build
 *
 * Regenerating from the built output is what keeps this honest — add a case
 * study with a character nobody used before and the next run picks it up. The
 * safety set covers what content is likely to reach for anyway, so a single
 * stale run cannot produce a missing glyph in normal prose.
 */

import { readdirSync, readFileSync, writeFileSync, statSync } from 'node:fs';
import { join, extname } from 'node:path';
import subsetFont from 'subset-font';

const DIST = 'dist';
const SOURCE = 'scripts/font-sources';
const OUT = 'public/fonts';

/**
 * Characters we keep whatever the current copy happens to contain: the printable
 * ASCII range, the punctuation good typography reaches for, and the Ukrainian
 * alphabet so the second locale does not need a font rebuild to render at all.
 */
const SAFETY =
  Array.from({ length: 95 }, (_, i) => String.fromCharCode(32 + i)).join('') +
  '“”‘’—–…·•±×÷≥≤≈°§¶©®™€£₴¥№' +
  'АБВГҐДЕЄЖЗИІЇЙКЛМНОПРСТУФХЦЧШЩЬЮЯ' +
  'абвгґдеєжзиіїйклмнопрстуфхцчшщьюя';

function walk(dir) {
  return readdirSync(dir).flatMap((name) => {
    const full = join(dir, name);
    return statSync(full).isDirectory() ? walk(full) : [full];
  });
}

/** Text nodes only — tag names and attribute values are never rendered. */
function textOf(html) {
  return html
    .replace(/<script[\s\S]*?<\/script>/g, ' ')
    .replace(/<style[\s\S]*?<\/style>/g, ' ')
    .replace(/<[^>]+>/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&nbsp;/g, ' ');
}

const pages = walk(DIST).filter((f) => extname(f) === '.html');
const used = new Set([...SAFETY]);
for (const page of pages) for (const ch of textOf(readFileSync(page, 'utf8'))) used.add(ch);

const chars = [...used]
  .filter((c) => c.codePointAt(0) > 31)
  .sort()
  .join('');
console.log(`pages read:       ${pages.length}`);
console.log(`distinct glyphs:  ${chars.length}`);

const JOBS = [
  { src: 'onest-400.ttf', out: 'onest-400-subset.woff2', family: 'Onest', weight: '400' },
  { src: 'onest-800.ttf', out: 'onest-800-subset.woff2', family: 'Onest', weight: '800' },
  {
    src: 'jetbrains-mono-400.ttf',
    out: 'jetbrains-mono-400-subset.woff2',
    family: 'JetBrains Mono',
    weight: '400',
  },
];

let before = 0;
let after = 0;
const faces = [];

for (const job of JOBS) {
  const source = readFileSync(join(SOURCE, job.src));
  const subset = await subsetFont(source, chars, { targetFormat: 'woff2' });
  writeFileSync(join(OUT, job.out), subset);
  before += source.length;
  after += subset.length;
  faces.push({ ...job, bytes: subset.length });
  console.log(
    `  ${job.out.padEnd(34)} ${(source.length / 1024).toFixed(1)} KB -> ${(subset.length / 1024).toFixed(1)} KB`,
  );
}

console.log(`\ntotal: ${(before / 1024).toFixed(1)} KB -> ${(after / 1024).toFixed(1)} KB`);

// The @font-face rules are generated from the same list that produced the files,
// so a family can never be declared that was not built.
const css = `/* ===========================================================================
   Self-hosted fonts — GENERATED by scripts/subset-fonts.mjs. Do not hand-edit.
   ---------------------------------------------------------------------------
   Subset to the characters the built site actually renders, plus a safety set
   covering printable ASCII, typographic punctuation and the Ukrainian alphabet.
   These files are preloaded, so their size sits directly in front of the first
   paint — which is why they are cut to content rather than to script.

   Static instances rather than one variable file: the design uses exactly two
   weights, and two subset instances came out smaller than one variable font
   carrying an axis nobody moves.

   Both families are under the SIL Open Font License 1.1 — see OFL-*.txt here.
   =========================================================================== */

${faces
  .map(
    (f) => `@font-face {
  font-family: '${f.family}';
  font-style: normal;
  font-weight: ${f.weight};
  font-display: swap;
  src: url('/fonts/${f.out}') format('woff2');
}`,
  )
  .join('\n\n')}
`;

writeFileSync('src/styles/fonts.css', css);
console.log('src/styles/fonts.css regenerated');
